/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tnt.logging.shared;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LogEvent implements org.apache.thrift.TEnum {
  LOG_EVENT_1(1),
  LOG_EVENT_2(2),
  LOG_EVENT_3(3);

  private final int value;

  private LogEvent(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LogEvent findByValue(int value) { 
    switch (value) {
      case 1:
        return LOG_EVENT_1;
      case 2:
        return LOG_EVENT_2;
      case 3:
        return LOG_EVENT_3;
      default:
        return null;
    }
  }
}
